### ISSUE TITLE
Pre-boarding search results from 'find records'

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#126]
When a user clicks into the 'Find Records' search box and then does a search; if there are no records they get 'No results'. There should also be an option to 'Add new vessel' on that search results page as the first item - whether or not search results have been returned. This way if there are no results - or the desired result is not in the list - the user does not have to go back to the previous page.

**Comment by VitaliyGre** [comment]
@Sheeri What is the difference from the Board Vessel screen? Looks like we will have two similar screens

**Comment by Sheeri** [comment]
Yes, the screens will be similar. It's two different ways to get to the same place.
