### ISSUE TITLE
Empty fields should not be saved to Realm/Atlas

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#15]
If a field is empty, it should not be saved as "empty string" in Atlas, the document should be sparse. If it's possible, the same for Realm, to minimize data being sent back and forth.<p>As of Monday, 18 May 2020 we're not ready for this to be done. We first need to get iOS, Android, web and Atlas working with a common data set. After that, I will assess whether making simple fields optional works with Realm Sync - and then we will decide whether to proceed.</p>

**Comment by Sheeri** [comment]
Waiting on Andrew to test if we're ready yet, he will test when he removes the ViewModel from iOS.

**Comment by am-MongoDB** [comment]
This isn't how Realm sync works. If the field exists in the mobile app's Objects then they will be in the Atlas document.

Issue https://github.com/WildAid/o-fish-android/issues/297 created to make `lastDelivery` optional
