### ISSUE TITLE
Disply most recent vessel photo on vessel page in search results

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#16]
Disply most recent vessel photo on vessel page in search results - this is the photo at the top of the screen that also shows "Board Vessel"

**Comment by VitaliyGre** [comment]
@Sheeri Is this Vessel Record screen? And the photo at the top is big image for the whole screen width?

**Comment by lebedynskyi** [comment]
@Sheeri @am-MongoDB 

Hello Guys.  What about a case when latest board does nto have Photo, but some previous (before latest report) has it.  Should we display the latest available photo ?
