### ISSUE TITLE
Up-version to Realm SDK v10.0.0-BETA.6

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#161]
[Latest list of Releases](https://github.com/realm/realm-java/releases)

**Comment by lebedynskyi** [comment]
@am-MongoDB 
@Sheeri 

Seems library is deployed with some errors. It says next error:

Could not GET 'http://oss.jfrog.org/artifactory/oss-snapshot-local/io/realm/realm-gradle-plugin/10.0.0-BETA.6/realm-gradle-plugin-10.0.0-BETA.6.pom'.

Received status code 409 from server:
