### ISSUE TITLE
Duty report review when going off duty - ability to "go back" and not go off-duty

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#17]
confirmation. Before or after shift review (time and boardings)?

**Comment by VitaliyGre** [comment]
@Sheeri Need design and flow

**Comment by Sheeri** [comment]
Design and flow as per https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937302

**Comment by VitaliyGre** [comment]
Fixed in scope #18
