### ISSUE TITLE
When going off duty- ability to change on/off-duty time

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#18]
shift review - before or after showing reports?

**Comment by VitaliyGre** [comment]
@Sheeri Need design

**Comment by Sheeri** [comment]
Design as per https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937302

**Comment by VitaliyGre** [comment]
@Sheeri When I switch the button and go off duty - how can I change time? Do we need additional dialog for this or additional screen?

**Comment by Sheeri** [comment]
As per the design at https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937302 you change the time with the pencil and then the time picker (or writing in the time), the same as how you can edit it when you board a vessel.
