### ISSUE TITLE
 Business listings aren't complete

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#185]
Business listings seem to be limited to the last 5 boarding records; it should be more like vessels, where all the records in the Realm are shown.

Searching for "Johnson" - I should see H.B. Johnson, but I don't:
![Screen Shot 2020-07-28 at 3 26 30 PM](https://user-images.githubusercontent.com/1767528/88711800-b838b100-d0e6-11ea-8b9a-b27cad555d67.png)

Searching for "Test" - I should see more than one record:
![Screen Shot 2020-07-28 at 2 03 17 PM](https://user-images.githubusercontent.com/1767528/88711832-c71f6380-d0e6-11ea-8c9e-56bb01aa5670.png)

Here's the data, looking from July 1st onwards (I limited it because I didn't want to see a ton of records).

MongoDB Enterprise atlas-l4abbo-shard-0:PRIMARY> db.BoardingReports.aggregate([{$match: {   agency:'Ecuadorian Galapagos', 'vessel.lastDelivery.business': {$ne: ''}, timestamp: {$gt : ISODate("2020-07-01 00:00:00.000Z")} }}, {$sort: {   timestamp: -1 }}, {$project: { 'vessel.lastDelivery.business': 1, timestamp: 1, _id: 0 }}]);
{ "timestamp" : ISODate("2020-07-28T17:17:43.407Z"), "vessel" : { "lastDelivery" : { "business" : "Jaws" } } }
{ "timestamp" : ISODate("2020-07-28T17:16:56.318Z"), "vessel" : { "lastDelivery" : { "business" : "Another business" } } }
{ "timestamp" : ISODate("2020-07-28T17:16:22.183Z"), "vessel" : { "lastDelivery" : { "business" : "Test business" } } }
{ "timestamp" : ISODate("2020-07-28T16:55:34.351Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman Dentistry" } } }
{ "timestamp" : ISODate("2020-07-28T16:19:35.063Z"), "vessel" : { "lastDelivery" : { "business" : "Legal seafoods" } } }
{ "timestamp" : ISODate("2020-07-21T14:24:10.800Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-21T08:38:35.132Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-17T14:24:23.396Z"), "vessel" : { "lastDelivery" : { "business" : "!Test" } } }
{ "timestamp" : ISODate("2020-07-17T14:23:34.417Z"), "vessel" : { "lastDelivery" : { "business" : "!Test" } } }
{ "timestamp" : ISODate("2020-07-17T14:22:55.046Z"), "vessel" : { "lastDelivery" : { "business" : "! Test" } } }
{ "timestamp" : ISODate("2020-07-14T14:06:25.805Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-14T13:29:18.818Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman" } } }
{ "timestamp" : ISODate("2020-07-14T12:45:30.279Z"), "vessel" : { "lastDelivery" : { "business" : "P. Sherman" } } }
{ "timestamp" : ISODate("2020-07-09T09:42:53.703Z"), "vessel" : { "lastDelivery" : { "business" : "H.B. Johnson" } } }
{ "timestamp" : ISODate("2020-07-06T10:18:36.956Z"), "vessel" : { "lastDelivery" : { "business" : "P.Merlock Industry" } } }

**Comment by lebedynskyi** [comment]
@Sheeri @am-MongoDB 

I did investigation. And I didn't find any issues.

- Application does not have a ny limitation in cound of items. It will display as many as it find.
- Application according #147 it has some limitation by pair of Bussines and Location - it uses realm.distinct(BUSSINES, LOCATION)

I think there is some issue or delay in sync between Atlas and Android client.  

Here a list of items (filtered without empty bussines):
{date:Thu Jan 01 00:00:00 GMT 1970},{location:Another locationWith another line},{business:Another business},{attachments:Attachments}], 
{date:Thu Jan 01 00:00:00 GMT 1970},{location:Nantucket, MA},{business:Jaws},{attachments:Attachments}], 
{date:Fri Jul 24 16:19:06 GMT 2020},{location:Northern aveSeaportboston, MA},{business:Legal seafoods},{attachments:Attachments}], 
{date:Tue Jul 21 16:10:06 GMT 2020},{location:Northern aveSeaportboston, MA},{business:Legal seafoods},{attachments:Attachments}], 
{date:Thu Jul 30 15:33:43 GMT 2020},{location:2884 Bunsen ave Ventura Ca},{business:Ocean Pride},{attachments:Attachments}], 
{date:Tue Jul 21 15:00:53 GMT 2020},{location:2884 Bunsen ave Ventura Ca},{business:Ocean Pride},{attachments:Attachments}], 
{date:Fri Apr 24 23:30:09 GMT 2020},{location:2884 Bunsen ave Ventura Ca},{business:Ocean Pride},{attachments:Attachments}], 
{date:Wed Jul 22 23:45:01 GMT 2020},{location:2884 Bunsen ave Ventura Ca},{business:Ocean Pride},{attachments:Attachments}], 
{date:Sat Apr 18 21:30:57 GMT 2020},{location:2884 Bunsen ave Ventura Ca},{business:Ocean Pride},{attachments:Attachments}],
{date:Mon Jul 06 16:56:00 GMT 2020},{location:42 Wallaby WaySydney, Australia},{business:P. Sherman Dentistry},{attachments:Attachments}], 
{date:Sat Jul 18 17:16:00 GMT 2020},{location:Test location},{business:Test business},{attachments:Attachments}

**Comment by Sheeri** [comment]
OK. I will check again this week, maybe I was testing with the wrong Agency.

**Comment by lebedynskyi** [comment]
@Sheeri , re-checked it again. Didin't find any issues.  Noticed that IOS app has the same data

**Comment by Sheeri** [comment]
This is a Realm sync issue! (The entry I looked at had empty arrays for photo IDs and EMS, and wasn't syncing to Realm because of it).
