### ISSUE TITLE
Change location of localization files if possible

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#186]
I see that the localization folders are in https://github.com/WildAid/o-fish-android/tree/main/app/src/main/res

However, the localization folders are mixed in with other resource files. Can we make a folder called "l10n" or similar, and put all the "values" folders in that folder? That way there's one folder to go to, to see all localization folders, and only those folders.

**Comment by lebedynskyi** [comment]
@Sheeri 
Did investigation. 
Android supports using different location for resources, but unfortunatelly it does not support for diffrent string files especcially overrided.

**Comment by Sheeri** [comment]
OK. It does seem like this is the "Standard" as per https://developer.android.com/guide/topics/resources/localization. Will close.
