### ISSUE TITLE
Use MenuData data for forms

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#187]
Please use the information in the MenuData collection for the following drop downs:

emsTypes array to populate Vessel->Electronic Monitoring System->EMS Type
fisheries array to populate Activity->Activity
activities array to populate Activity->Fishery
gear array to populate Activity->Gear
species array to populate Catch->Catch X->Species
violationCodes array to populate Violations->Violation (1st line)
violationDescriptions array to populate Violations-> Violation (2nd line)

I'm unsure these are properly used because there are translations for these arrays in app/src/main/res/values/strings.xml. That indicates they are hard-coded per language, instead of variable per agency.

Please make sure they are not hard-coded in translations, and that the values from MenuData are used. Thanks!

**Comment by Sheeri** [comment]
I'm pretty sure this was completed for release 20 (7/28) but the translations are still there in the strings.xml files and should be removed.

**Comment by VitaliyGre** [comment]
@Sheeri Translations are left in case the Menu Data is empty. We can remove translations if we do not need hardcoded data for the case when internet will be unavailable

**Comment by Sheeri** [comment]
We should hardcode "Other" for the lists that have "Other" in case the internet cannot synchronize, but that's the only value we should hard-code. Everything else should be from form data. So if form data is not available, we should see one item that is "other". (Except for flag state preference, if that doesn't exist there should be no preference and the list is just the alphabetical list of countries).
