### ISSUE TITLE
Country list should be internationalized

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#197]
The country list for flag state should be internationalized. For example 'United States' is the English; 'Estados Unidos' is Spanish; 'États Unis' is French. If you can provide the localized lists for Spanish and French that would be awesome - but if not that's OK too - I can provide them.

**Comment by lebedynskyi** [comment]
@Sheeri  @am-MongoDB 
Since the original data list is comming from Database.  The solution for this ticket is  add localized Flag states into Realm DB or introduce new Localization mechanism.  Default will not work with it. 

Anyway we need localized list of Flag States

**Comment by Sheeri** [comment]
You're right - the list of flag states themselves (all the countries) comes from the OS, and the choice comes from the database. No localization needed.
