### ISSUE TITLE
Flag State Agency Menu preference not showing up

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#206]
The top of the flag state list is always "Ecuador" and "Panama" even when the data for the agency is otherwise (blank, or if there are other values like "United States").

If the agency data is blank or missing for the form data for Flag State, nothing should show up at the top (e.g. it starts at Afghanistan, Albania, Algeria, etc.) Otherwise the countries should be shown at the top in the order they are given (e.g. United States, Ecuador, Gabon should show up like that, before Afghanistan, Albania, Algeria).

**Comment by Kirill250402** [comment]
@Sheeri, I checked this thing, two locales comes to app = "EC" and "PA", these comes from DB as I think.
I think it's not a problem with app.

**Comment by Sheeri** [comment]
Hi @Kirill250402 to test this out, change a value in the database and see what happens. You can test out:

Valid values like “US” and “FR”
No values
Invalid values like “hello”

The first one should have the top two being United States and France. The last two should have no special values. 

I found that the middle example, when I tried, gave me Ecuador and Panama (EC and PA) at the top.

**Comment by lebedynskyi** [comment]
@Sheeri  as we discussed - I close this issue. Since there is no issue on client side.
