### ISSUE TITLE
Reason for Amber/Red

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#218]
When Red or Amber is selected - the note field 'Reason for Red' or 'Reason for Amber' should appear and be blank. The user should not have to add a note to get that to appear.

**Comment by lebedynskyi** [comment]
Hi @Sheeri .. Do we still need stapple button for Risk screen ?

**Comment by Sheeri** [comment]
If we are always having a reason we don’t need to attach a note, we can get rid of that button.
