### ISSUE TITLE
Activate field or section upon adding

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#221]
Once a field or section has been added - that field should be active and visible above the keyboard. Only text fields should be active. e.g. when EMS is added the EMS type field should be active.

**Comment by lebedynskyi** [comment]
Hi @Sheeri .. I've checked all application and found that EMS field is a selection of choice. It is prohibited to type ems type.

Only crew member could be written by keyboard. Everything else is a choice from the list when user click on this field..
