### ISSUE TITLE
Overlay MPAs on Google Maps

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#23]
Need to figure out how this is done. Can it be done with polygons?

**Comment by Sheeri** [comment]
Example polygon for Galapagos MPA:
      $geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [ -88.03310394, -0.534202465 ],
            [ -88.28613281, -2.811371193 ],
            [ -93.12011719, -2.635788574 ],
            [ -95.14160156, -0.790990498 ],
            [ -96.28417969, 2.372368709 ],
            [ -94.26269531, 4.302591077 ],
            [ -91.01074219, 3.250208562 ],
            [ -88.03310394, -0.534202465 ]
          ]
        ]
      }

**Comment by VitaliyGre** [comment]
@Sheeri Need design. In scope of #22 MPA was added and now they looks like this
![device-2020-06-12-172205](https://user-images.githubusercontent.com/16455151/84515033-991bc680-acd4-11ea-909b-c30cd5700831.png)

**Comment by Sheeri** [comment]
This is being worked on in #502 .
