### ISSUE TITLE
Android Realm schema for MPA data (polygons)

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#24]
We can use polygons with the geospatial data�.

**Comment by Sheeri** [comment]
Example polygon for Galapagos MPA:
      $geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [ -88.03310394, -0.534202465 ],
            [ -88.28613281, -2.811371193 ],
            [ -93.12011719, -2.635788574 ],
            [ -95.14160156, -0.790990498 ],
            [ -96.28417969, 2.372368709 ],
            [ -94.26269531, 4.302591077 ],
            [ -91.01074219, 3.250208562 ],
            [ -88.03310394, -0.534202465 ]
          ]
        ]
      }

**Comment by Sheeri** [comment]
@EduardHarutyunyan97 I think you're already working on this ticket, so I assigned it to you.
