### ISSUE TITLE
Change 'on duty' and 'off duty' language

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#246]
We are not using the concept of 'on duty' and 'off duty' any more. 
The Android design for the toggle is at https://mongodb.invisionapp.com/share/AHXMRTBBSCQ#/screens/420974310_Android-Home-Menu-Off_Duty 

The modal confirmation is at https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937301_Modal-Off_Duty_Alert 

The 'duty report' should now be Patrol Summary as per https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/423507970_Home-On_Duty-Switch_Off

**Comment by lebedynskyi** [comment]
@Sheeri @am-MongoDB 

We use "On Duty" and "Of Duty"  keywords to determine status of oficer. 
Should we update this values in Realm ?

**Comment by am-MongoDB** [comment]
I'd say not to change what we store in Realm

**Comment by Sheeri** [comment]
As discussed in a meeting, we are not changing what we store in Realm (as that would involve localization issues too).
