### ISSUE TITLE
Icon colors should be #666666

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#247]
Attachment icon; edit icon; and camera/photo icon color should be #666666 as per https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937416_Boarding-Catch-Add_Catch and https://mongodb.invisionapp.com/share/RWX43EEF567#/screens/415937455_Boarding-Notes

**Comment by tomorisakura** [comment]
hi i'm new on open source contribute , can i try this issue ?

**Comment by Sheeri** [comment]
Hi! There's already a pull request on this,  so someone else is already working on it.  I will work on assigning it properly, they started on it before our guidelines were in place on how to ask for an issue. 

In a few days we will have some issues for making dark mode happen,  which will be similar to this issue (changing some colors if the deal mode flag is set)

**Comment by yoobi** [comment]
Sure, is everything okay concerning the pull request ?

**Comment by Sheeri** [comment]
@yoobi I'll make sure that it's reviewed soon!
