### ISSUE TITLE
App should react to changes in Realm

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#257]
From review by Realm engineering team: 

Repository isn’t reactive. Everything in the UI is pull-based. I.e. you might not notice if changes are coming in from other devices. This generally goes against how we recommend people building UI’s and leveraging Realm strengths.

**Comment by lebedynskyi** [comment]
@Sheeri 
@am-MongoDB 

Do we really need this?

We do not have a lot of screens with data from realm. I see few screens and I am not sure we need it.
- Record search (could be added new report for another device)
- Vessel details  (could be added new report from anotyher device)
- Report details (Unable to modifym no reason to use autoupdate)


Here we can see 2 flow. Adding new Entity and updating of entity.  I am not sure Realm support 1 case..

**Comment by Sheeri** [comment]
We definitely need it for search, so new reports show up right away. We also need it to demonstrate to others how it's done. This app may not strictly need it for all screens; however, this app is also a learning tool and it's natural to have push functionality for search.

**Comment by am-MongoDB** [comment]
Blocked on the new SDK that adds Coroutine support
