### ISSUE TITLE
"+ Add New Vessel" should not appear in the "Find records" search

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#259]
"+ Add New Vessel" should only appear in pre-boarding search, not the "find records" search.

**Comment by lebedynskyi** [comment]
@Sheeri it was added in #198  
Should we remove it from Find Records?

**Comment by Sheeri** [comment]
Correct, please remove it from Find Records but keep it in the search when "Board Vessel" is clicked.
