### ISSUE TITLE
Empty captain/crew show up when issuing a violation

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#270]
When doing a boarding, I went right to "Violation", skipping the "Crew" section. 

When I clicked "Issued To" on the violation screen, I saw an empty captain and crew member. This screen should not show items that have no name AND no license number.

![Screenshot_1599144518](https://user-images.githubusercontent.com/1767528/92130845-31f14800-edd3-11ea-9ff1-6affe70ca672.png)

**Comment by lebedynskyi** [comment]
Closed in #295
