### ISSUE TITLE
Pre-boarding search record uniqueness

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#284]
In pre-boarding search records should be unique by name AND permit number. Currently it is based only on name so two vessels with the same name and different permit number show up as one record but they should show up as 2 different ones.

**Comment by Sheeri** [comment]
Screenshot of mobile app:
![Screen Shot 2020-09-09 at 4 36 42 PM](https://user-images.githubusercontent.com/1767528/92650989-be5fa700-f2ba-11ea-9993-e7d8d60cf4fc.png)

Screenshot of web app for vessels named "orca":
![Screen Shot 2020-09-09 at 4 37 53 PM](https://user-images.githubusercontent.com/1767528/92651258-d1727700-f2ba-11ea-917c-95b525da9796.png)


What we should see is 2 records in the mobile app for Orca - one for permit 12345 and one for permit 98765. Photos, risk color, etc should all be separated by name + permit number.

**Comment by lebedynskyi** [comment]
@Sheeri .

Seems everything is OK.. Maybe there is some delay between syncs?
![image](https://user-images.githubusercontent.com/58213750/93611209-b0a2d380-f9d6-11ea-95b7-bb64f1a1bc56.png)

**Comment by Sheeri** [comment]
Great, closing!
