### ISSUE TITLE
make lastDelivery optional

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#297]
If the user doesn't provide any input, then `lastDelivery` should be set to `null`.

The app must correctly display existing reports where `lastDelivery` is set to `null`

**Comment by lebedynskyi** [comment]
@am-MongoDB  I did this functiuonality week ago according
#282 
Now if this section is null - the section will be hidden in Report details.. Do wee need to change anythingh ?

**Comment by am-MongoDB** [comment]
I thought I'd already raised an issue but couldn't find the PR. Nothing else to do - thanks
