### ISSUE TITLE
Add a flag to the `Report` model to indicate that the report is currently being edited

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#303]
Just the model/view-model work, doesn't include linking it to the UI

This is the PR that makes the same change for iOS: https://github.com/WildAid/o-fish-ios/pull/284

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/crgxnjIM/305-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by Sheeri** [comment]
@lebedynskyi this is the first ticket to enable draft functionality.

**Comment by lebedynskyi** [comment]
Thanks. Will take a look on this.
