### ISSUE TITLE
logging out with draft boardings

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#313]
If a user clicks 'Log Out' while they have draft boardings a modal should appear warning that drafts will be deleted - as per the design at https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430515895_Modal-Logout

**Comment by am-MongoDB** [comment]
This should use the cascading delete function being added under https://github.com/WildAid/o-fish-android/issues/323

**Comment by Sheeri** [comment]
The customer has requested that drafts be able to be saved across mobile to web - that is, a SAVED draft boardings that hasn't been submitted, should NOT be deleted.

I apologize for the change in functionality; this reverses what we were told earlier.

**Comment by Sheeri** [comment]
closing; this is no longer an issue.
