### ISSUE TITLE
Add cascading delete to Report model and view model

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#323]

**Comment by am-MongoDB** [comment]
This is how we did it for the iOS app https://github.com/WildAid/o-fish-ios/pull/302

**Comment by Sheeri** [comment]
@lebedynskyi Not sure what you're waiting on. This would enable deleting drafts, which I believe you have. Can you and @am-MongoDB chat to see if this needs work or can be closed?
