### ISSUE TITLE
Display error message if user provides the wrong username/password

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#336]

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by am-MongoDB** [comment]
This is what iOS displays 
![image](https://user-images.githubusercontent.com/14197449/94266927-adf23200-ff32-11ea-91a2-0291aa0dfadd.png)
