### ISSUE TITLE
Refresh user avatar image

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#337]
When the user's profile picture is changed from another device, it should also change in the Android app. At present, it doesn't change even if the app is force-quit or the user logs back out and back in again. The view should take the latest image from Custom data whenever the view refreshes

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/lom20Pzv/326-raise-new-issues-resulting-from-using-testing-the-apps)

**Comment by Sheeri** [comment]
Could not reproduce:

Steps:
I logged into the Android app in the dmssx environment
Then logged into the Web app
Changed my avatar in the web app
Logged out of the Android app and logged back in, avatar was changed.
