### ISSUE TITLE
For Flag State on Vessel Information Store Country Code

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#354]
On the Vessel Information page - when the user chooses a menu option for Flag State - the country code should be stored in the database - not the full name of the country. e.g. 'us' not 'United States' or 'ec' not 'Ecuador'.

When it is displayed in the application, e.g. in the patrol summary, editing a draft boarding or in the 'find records' path, it should show up as the country name (e.g. 'United Kingdom' not 'GB').

**Comment by jokopriyono** [comment]
@o-fish-wildaid you mean alpha-2 code from ISO 3166-1 standard?
