### ISSUE TITLE
Add Dark Mode button and change the 'Me' page accordingly

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#368]
Users frequently find themselves in situations where they are using the app in very bright sunlight, or at night. Please add a Dark Mode button, and change the 'Me' page accordingly. 

This is the screen when the user clicks their avatar on the home screen. 

The screen should look like this - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me
Dark mode is off by default, and has the light background; when Dark mode is toggled on, the dark theme should be applied. 

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode  
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode   
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

**Comment by thearavind** [comment]
Hi @Sheeri Can I work on this issue

**Comment by Sheeri** [comment]
@thearavind Yes, please do! I've assigned it to you.
