### ISSUE TITLE
Dark Mode for Login page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#369]
This issue depends on #368 being completed. 

When Dark Mode is on - the login page should look like this: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591777_Log_In

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not).

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

**Comment by ardlank** [comment]
@o-fish-wildaid can I do this?

**Comment by ardlank** [comment]
PR: https://github.com/WildAid/o-fish-android/pull/387

**Comment by am-MongoDB** [comment]
Hi @ardlank I've assigned the issue to you. Welcome to the project!

**Comment by Sheeri** [comment]
![Screenshot_20201006-143737_O-FISH](https://user-images.githubusercontent.com/1767528/95246280-3e0d6280-07e2-11eb-9d31-d1e38179711c.jpg)
