### ISSUE TITLE
Dark Mode for draft boardings page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#371]
This issue depends on #368 being completed. 

When Dark Mode is on - the draft boardings page should look like this: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591780_Draft_Boardings

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not), and colors should be stored in:
app/src/main/res/values-night/colors.xml 
app/src/main/res/values/colors.xml 

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

**Comment by ippschi** [comment]
I would like to tackle this one

**Comment by ippschi** [comment]
Actually, after seeing what the previous contributors did, I would like you to consider to not let multiple people do those dark mode tasks. It seems that the available colors from the design library are not reused but always defined again and again.

**Comment by Sheeri** [comment]
@ippschi yes, I realized that mistake too late. I have cleaned up some of it, and added to the description:

_Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not), and colors should be stored in:
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml_

If you would like to pick this up again, it would be great - since you're already aware of the pitfalls and will make sure to code it optimally, reusing the available colors.

**Comment by ippschi** [comment]
Yes, I will work on this.

**Comment by Sheeri** [comment]
Thanks, Andre, I have assigned this issue to you.

**Comment by ippschi** [comment]
Since I wrote about my concerns regarding the colors and the future use of them I just created a pull request with the proposal of having a separate colors file for the "brand" colors. Basically all the colors defined by the designers in invisionapp. (This can also be exported if not mistaken).

**Comment by ippschi** [comment]
The PR for the fix was also added
