### ISSUE TITLE
Dark Mode for Activity page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#383]
This issue depends on #368 being completed. 

When Dark Mode is on - the Activity page should look like this: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591790_Boarding_-_Activity

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

Both dark and light modes should follow the color key and specs above (it is possible that the current light mode is not), and colors should be stored in:
app/src/main/res/values-night/colors.xml 
app/src/main/res/values/colors.xml 

Please make sure to TEST your build on a device or emulator to verify everything has changed - you can get a login and realm-app-id with easy instructions at https://wildaid.github.io/contribute/sandbox.html

**Comment by ashwinpilgaonkar** [comment]
Can I work on this?

**Comment by Sheeri** [comment]
Hello @ashwinpilgaonkar, thanks for offering to work on this! I have assigned it to you.

**Comment by ashwinpilgaonkar** [comment]
Hey @Sheeri looks like this page is already dark mode ready. Perhaps I could work on a different issue instead - such as https://github.com/WildAid/o-fish-android/issues/373

**Comment by Sheeri** [comment]
Will do. Closing this issue.....
