### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by ippschi** [WildAid/o-fish-android#395]
**Describe the bug**
An "Android resource linking failed" error is thrown in Android Studio:
app/src/main/res/layout/item_custom_tab.xml:8: AAPT: warn: generated id 'android:id/text1' for external package 'android'.

**To Reproduce**
Steps to reproduce the behavior in Android Studio:
1. Go to file app/src/main/res/layout/item_custom_tab.xml:8
2. See error "Cannot resolve symbol"
(Probably depends on how you configured your Android Studio to handle errors)

**Expected behavior**
Correct naming or in this case: No naming needed at all (probably copy paste mistake)

The fix will be submitted immediately as a PR

**Comment by ippschi** [comment]
The fix was submitted as a PR

**Comment by ippschi** [comment]
The first pull request was wrong since my Android Studio apparently hadn't recovered from the error yet. The new one is tested after a fresh clean.

**Comment by Sheeri** [comment]
Was able to reproduce; when building, in the section "Configure project :app".
