### ISSUE TITLE
Notification of "are you still at sea"? should open the app when selected

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#399]
**Is your feature request related to a problem? Please describe.**
Currently there  is a notification if you leave the app but are still "at sea" - after 4 hours a notification will pop up saying "are you still at sea?"

However, all I can do is close the notification. Tapping on it does nothing.

**Describe the solution you'd like**
I would like it to open O-FISH when I tap the notification. (or double-tap, or whatever the standard is).

**Comment by thearavind** [comment]
@Sheeri Please assign this to me, I will work on this
