### ISSUE TITLE
Dark mode tries to save to realm

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#406]
**Describe the bug**
Dark mode is trying to sync to the existing Realm schema with fields that don't exist. This means that drafts and boardings don't save properly.

**To Reproduce**
1. Login
2. Click the profile avatar in the upper right
3. Go into Dark Mdoe
4. Create a boarding and submit it.
5. see the error: "an error occurred while saving"

I see this error in the emulator. On my physical device, I don't see an error, however the boardings don't get saved into the database.

In the logs I see:
Ending session with error: failed to validate upload changesets: could not find primary key field "_id" in schema "DarkMode" (ProtocolErrorCode=212)

**Expected behavior**
In #390, our lead developer said "Probably better to just store it as local state in the device, whether outside of Realm or in a non-sync’d realm, as it’s reasonable that someone would want different values on say their phone and tablet."

That's what should happen; regardless of the dark mode status, the boarding reports should be able to save.

**Comment by Sheeri** [comment]
@thearavind I think you would have the most context to solve this - would you like to take a try at it?

**Comment by thearavind** [comment]
Yes @Sheeri please assign this to me I can do it

**Comment by Sheeri** [comment]
Fantastic @thearavind ! I have assigned this to you.
