### ISSUE TITLE
App crashes when swiping/double tapping map in basic information page when location is turned off.

### ISSUE THREAD

**Issue by sunny52525** [WildAid/o-fish-android#425]
When you open the new boarding page ,Basic information page comes up with a map. And if you touch the map when location service is turned off ,the app crashes.

1. Turn off location
2. Open the app
3. Click a new Boarding or edit old one
4. Swipe or double tap the map in basic information page.

> Here is a gif showing the issue
![20201020-141518](https://user-images.githubusercontent.com/30768018/96565996-b005a180-12e2-11eb-989a-c40db8ce148a.gif)

 - Device: MI A3
 - OS: Android 10

**Comment by sunny52525** [comment]
I put a check before updateMarker function to see if location is turned on or off, then it works fine. Let me know if I should create a PR to fix this issue?

> After Applying the check
 
![20201020-142724](https://user-images.githubusercontent.com/30768018/96566604-679ab380-12e3-11eb-9149-124ba0a1f0ac.gif)

**Comment by Sheeri** [comment]
@sunny52525 yes, please do submit the PR! Thanks for taking the initiative - that's one of the things that makes a great open source contributor - you find a problem and report it.....and going even further, you fix it!

**Comment by Sheeri** [comment]
Hi! I was able to reproduce this issue. Thanks for the bug report. Will test the fix now :D
