### ISSUE TITLE
Toggle switch in light mode needs a green background

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#427]
**Describe the bug**
When in light mode, the toggle has a white background, not a green one.

The screen should look like the bottom left at - https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591779_Me

Color key for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591768_Color_Key_-_Light_Mode
Color key for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591769_Color_Key_-_Dark_Mode
Component Color specs for light mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591770_Component_Colors_-_Light_Mode
Component Color specs for dark mode: https://mongodb.invisionapp.com/share/PCYZ6ZW7FR8#/screens/433591771_Component_Colors_-_Dark_Mode

**Screenshots**
Note that "Not At Sea" should have the green background, indicating it's on.
![Screenshot_20201019-171426_O-FISH](https://user-images.githubusercontent.com/1767528/96729384-16420100-1383-11eb-9b3c-ec5923e9ad03.jpg)

**Comment by aayush287** [comment]
@Sheeri I would like to work on this. Can you assign it to me?
