### ISSUE TITLE
Need a way to remove a violation

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#453]
If you add a violation on the Violation screen there is no way to remove it. It can be changed to a different violation but not removed.

**Comment by Sheeri** [comment]
Hi @EduardHarutyunyan97 - here is the design flow of what's supposed to happen: https://mongodb.invisionapp.com/console/share/RWX43EEF567/587686014/play

Notice that the design has a "- Remove violation 1" place - that is not reflected in the android version right now, and needs to be implemented.
