### ISSUE TITLE
On Basics screen: Cannot edit lat/lon directly

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#459]

**Comment by EduardHarutyunyan97** [comment]
@Sheeri maybe you would add the location name(" country, city ") and see it in the application?

**Comment by Sheeri** [comment]
No, in this case the user would have a GPS system on their boat with more accurate GPS that they want to type in. So it's really just for entering in numbers.

**Comment by EduardHarutyunyan97** [comment]
@Sheeri this one is done :) 

Here is the PR
 https://github.com/WildAid/o-fish-android/pull/484
