### ISSUE TITLE
Cannot add more than one note

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#460]
Adding a note works. If I add a 2nd note it blanks out the first note.

**Comment by EduardHarutyunyan97** [comment]
@Sheeri you also can add notes on the "Notes" page.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/46895882/161537811-3b0d5247-6e86-4c55-91da-475bbfed1754.png">

**Comment by Sheeri** [comment]
Cannot replicate in the current version (1.0.10)
