### ISSUE TITLE
Once you pick a violation result or issued to is not required for validation

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#462]

**Comment by EduardHarutyunyan97** [comment]
@Sheeri Can you explain to me a flow of navigation, or please write a description under this ticket :)

**Comment by Sheeri** [comment]
here's a link to an InVision flow: https://mongodb.invisionapp.com/console/share/RWX43EEF567/587686014/play

If there is a violation selected from the pull-down menu "Violation", the section "Result of violation" - warning or citation - is required.
Also if there is a violation, "issued to" should be required. All violations are issued to someone.

Hope that helps!

**Comment by EduardHarutyunyan97** [comment]
@Sheeri  this task is done :) 
here is the link https://github.com/WildAid/o-fish-android/tree/o_fish_bf_462

please confirm the last task PR for merging it into the "dev" branch
