### ISSUE TITLE
Paperclip/pencil file duplicates

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#467]
Why are there so many files? why not just one of each? (see PR 360) The files for pencil and paperclip should be reused when possible. If we need different file formats or something, please let me know.

**Comment by EduardHarutyunyan97** [comment]
@Sheeri @o-fish-wildaid 

I saw that in project files there are no unused icons of pencil and paperclip.
All assets are vector files. Vector files change their sizes dynamically, depending on screen size.

**Comment by Sheeri** [comment]
OK, great. Thanks for investigating.
