### ISSUE TITLE
'+ New Business' appears only after search.

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#470]

**Comment by EduardHarutyunyan97** [comment]
@Sheeri if you clicked on a business "edit text" view, it opens the existing businesses, which was saved in a Realm DB.
If you clicked "+New Business" on a search page, you can write a new business name by clicking the business "edit text" view. After writing the new business name it's saved into DB.

So what am I supposed to do ? :)

**Comment by Sheeri** [comment]
Apologies for not being clear - the "+ New Business" item should appear at the TOP of the list of businesses, not at the bottom.

**Comment by EduardHarutyunyan97** [comment]
@Sheeri done :) 
 https://github.com/WildAid/o-fish-android/pull/481
