### ISSUE TITLE
Clicking on an MPA gets more information

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-android#501]
As per the design at https://mongodb.invisionapp.com/console/share/8XXUAUP2YZS/587697150 - when a user clicks inside an MPA they should see more information about the MPA. This information is stored in the MenuData collection.

**Comment by Sheeri** [comment]
Here's an example of the information - name, country, description, and info are used for this:

<img width="1015" alt="Screen Shot 2022-05-13 at 11 01 12 AM" src="https://user-images.githubusercontent.com/1767528/168311754-14e6b87a-d9f9-4b29-abeb-c80a71ae78e5.png">

**Comment by MikeyDubs** [comment]
@Sheeri
![location-shape](https://user-images.githubusercontent.com/49571712/168659088-77d10087-c4a8-4c6d-8186-3b5c848c792b.svg)

^^ Let me know if this works!
