### ISSUE TITLE
Recently Boarded Title

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#52]
In Board Vessel search and the Find Records search from the homepage: Recently Boarded title should be #818181 As per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.qy9manpdxfcf

**Comment by VitaliyGre** [comment]
We have already used #818181. Added Roboto Medium to be closer to design
