### ISSUE TITLE
Back Arrow Interaction - Find Records in both pre-board search locations

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#54]
In Board Vessel search and the Find Records search from the homepage: Back arrow should take users back where they just came from as per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.tjt6bu9b3qv8

**Comment by lebedynskyi** [comment]
@Sheeri 

This is native android behaviour to hide keyboard.
On Android we don't have another mechanism to hide keyboard. Thats why if user press back arrow it hides automatically. Next tap on back will close the screen

**Comment by Sheeri** [comment]
The back arrow shouldn’t have the same exact functionality as the triangle Android bottom button. Please let the triangle button has its own functionality, and the back arrow goes back to the previous screen on the first tap.

So if a user wants the keyboard to go away they can hit the triangle button, and if they want to go back they hit the back arrow at the top.

Note that if the user does make the keyboard go away, the back arrow at the top should still be there.
