### ISSUE TITLE
Previous Boardings

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#61]
Font weight should be medium. Pill text should be 12px and the pill should be larger to accommodate. Date should not be bold. Padding should be 16px. As per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.rdglysq5v2ji

**Comment by VitaliyGre** [comment]
Text size was already 12 dp. Increased to 13dp
