### ISSUE TITLE
Remove need to set `realm_url` in config

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-android#7]
The default URL is built into Realm SDK and so there should be no reason to have this as a non-defaulted config value

**Comment by lebedynskyi** [comment]
@am-MongoDB  Seems this issue is closed. We havealready done it before moving ti new repository..

**Comment by am-MongoDB** [comment]
If I don’t include `realm_url=https://realm.mongodb.com` in `local.properties`  then I can’t log in and get `D/Login: Cannot log in. Error http error code considered fatal`. The developer shouldn’t need to add this as the SDK should default to that base URL unless we override it in our code

**Comment by lebedynskyi** [comment]
This Issue should be fixed in #32
