### ISSUE TITLE
Add an item with a plus

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#95]

**Comment by Sheeri** [comment]
As per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.f8hlawaqqtdk - this is globally for any items added with a +:
The font styling should be 14px Regular
The + icon should be 20px
There should be 24px padding above and below each “Add Section” button
