### ISSUE TITLE
Icon for removing notes and photos

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#97]
As per https://docs.google.com/document/d/1P3mzpbmd1iaXudXnmArLdawOrDCdmhG4WMwXPC0682c/edit#bookmark=id.spqixwtwidb The remove icon should be the same size for each - should be about 20px, and centered between the field title and line below

**Comment by Sheeri** [comment]
This is globally, not just the screen that the example shows.

**Comment by lebedynskyi** [comment]
@Sheeri 
Input field is a default Android Material component. Unfortunatelly it does not have API to customize the place of image.  
We even not able to change size.. 

Now this image is centered vertically by the input field (Without header.). In that place where user is typing.  

To implement pixel perfect according design it could take up to 3 days. We need to invent new Custom view with ability to change size and place of image.  


For first solution I've changed the remove icon on the photos to be the same as in the input layout.

**Comment by lebedynskyi** [comment]
The size of icon was fixed in #138 
The place of icon is not so easy to fix. Decided to keep as is..
